---
title: "Ejercicios Strings R4DS"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
library(tidyverse)
library(datos)
```

```{r ejercicios}
#2.5.1 paste() and paste0() 

a <- c("a", "b", "c")
b <- c("w", "x", "y", "z")
paste(a, b)
paste0(a, b)

#2.5.2 join de los vectores: paste sep = " ", paste0 sin separador
# str_c es más parecido a paste0. Difieren en NA, str_c da como resultado NA, y paste y paste0 los  combina
str_c("a", NA); paste("a", NA); paste0("a", NA)
```

```{r}
#2.5.3 Use str_length() and str_sub() to extract the middle character from a string. What will you do if the string has an even number of characters?

a <- "abcde"

str_medio_1 <- function(a) {
  if(length(a) == 0) {
    a
  } else {
    l = str_length(a)
    y = l %/% 2
    z = l %% 2
    m = y + z
    str_sub(a, m, m )
  }
}
 
#otra manera
str_medio_2 <- function(a) {
  if(length(a) == 0) {
    a
  } else {
    L <- str_length(a)
    m <- ceiling(L / 2)
    str_sub(a, m, m)
  }
}
str_medio_1(a)
str_medio_2(a)

```

```{r}
#2.5.4 str_wrap(string, width = 80, indent = 0, exdent = 0)

thanks_path <- file.path(R.home("doc"), "THANKS")
thanks <- str_c(readLines(thanks_path), collapse = "\n")
thanks <- word(thanks, 1, 3, fixed("\n\n"))
cat(str_wrap(thanks), "\n")
cat(str_wrap(thanks, width = 40), "\n")
cat(str_wrap(thanks, width = 60, indent = 2), "\n")
cat(str_wrap(thanks, width = 60, exdent = 2), "\n")
cat(str_wrap(thanks, width = 0, exdent = 2), "\n")

sentences <- c("Jane saw a cat", "Jane sat down")
word(sentences, 1)
```

```{r}
# 2.5.5 ¿Qué hace str_trim()? (trim = recortar) ¿Cuál es el opuesto de str_trim()?
#str_trim elimina blancos de adelante y atras 
# str_squish() elimina blancos repetidos de medio

#El opuesto es str_pad
#str_pad(string, width, side = c("left", "right", "both"), pad = " ")
rbind(
  str_pad("hadley", 30, "left"),
  str_pad("hadley", 30, "right"),
  str_pad("hadley", 30, "both")
)
```

```{r}
#4.2.6 Escribe una función que convierta, por ejemplo, el vector c("a", "b", "c") en la cadena a, b y c. Piensa con detención qué debería hacer dado un vector de largo 0, 1 o 2.
x <- c("a", "b", "c", "d")
agrega_y <- function(x, delim = ","){
n <- length(x)
  if (n < 2) {
    x
  } else if (n == 2) {
    # solo separar con "y"
    str_c(x[[1]], "y", x[[2]], sep = " ")
  } else {
    # separar con comas todos los elementos, excepto los dos último, que llevan una "y"
    str_c(c(str_c(x[seq_len(n - 2)], delim), 
            str_c(x[[n-1]], "y", x[[n]], sep = " ")), 
          collapse = " ")
  }
}
agrega_y(x)
x <- "a"
agrega_y(x)
```


```{r}
#2.7.1 Explica por qué cada una de estas cadenas no coincide con \: "\", "\\", "\\\". 
x <- "\\"
#str_view(x, "\") 
#lo toma como un escape pero no tiene otro caracter al que tenga que escapar
#str_view(x, "\\") 
#las dos barras dejan 1 pero serviría como escape que no esta definido
#str_view(x, "\\\")
#las dos barras dejan 1 que sería escape de algun caracter, pero como es tambien una barra cree que es el escape de otro caracter especial 
str_view(x, "\\\\") #las dos 1ras quedan como una barra, las dos ultimas como otra barra, entonces quedo "\\" que la primera es el escape de la segunda... ahí lo entendió como que se buscaba una barra.
```

```{r}
#2.7.2. Cómo harías coincidir la secuencia "'\?
x <- "\"'\\?"
writeLines(x)

str_view(x, "\\\"'\\\\")
```

```{r}
#2.7.3. Con qué patrones coincidiría la expresión regular\..\..\..? ¿Cómo la representarías en una cadena?
x <- c("abc.d.e.f", ".1. .3", ".a.b.c", "\\.\\.\\.")
str_view(x, "\\..\\..\\..")
```

```{r}
#2.8.1¿Cómo harías coincidir la cadena "$^$" de manera literal?
x <- "$^$ "
writeLines(x)
str_view(x, "\\$\\^\\$")

```

```{r}
# 2.8.2 Dado el corpus de palabras comunes en datos::palabras, crea una expresión regular que busque palabras:
 datos::palabras
#Empiecen con “y”.
str_view(palabras, "^y", match = TRUE)
#Terminen con “z”
str_view(palabras, "z$", match = TRUE)
#Tengan una extensión de exactamente tres letras.
str_view(palabras, "^...$", match = TRUE)
#Tengan ocho letras o más
str_view(palabras, "........", match = TRUE)

```

```{r}
#Crea una expresión regular que encuentre todas las palabras que:
#1. Empiecen con una vocal.
str_view(palabras, "^[aeiou]", match = TRUE)
#2.Solo contengan consonantes. (Pista: piensa en cómo buscar coincidencias para “no”-vocales.)
str_view(palabras, "^[^aáeéiíoóuúü]+$", match = TRUE)
#3.Terminen en ón, pero no en ión.
str_view(palabras, "[^i]ón$", match = TRUE)
#4.Terminen con ndo o ado.
str_view(palabras, "ndo$|ado$", match = TRUE)
```

```{r}
#2.9.2 ¿Siempre a una “q” la sigue una “u”?
 str_subset(palabras, "q[^u]") 
```

```{r}
#2.9.3 Escribe una expresión regular que permita buscar un verbo que haya sido escrito usando voseo en segunda persona plural (por ejemplo, queréis en vez de quieren).
a <- "queréis"
str_subset(palabras, "[áéíóú]is$") 
str_subset(a, "[áéíóú]is$") 
```
 **ojo no esta bien**
```{r}
#Crea una expresión regular que coincida con la forma en que habitualmente se escriben los números de teléfono en tu país. ojo no está bien!!!!
telefonos <- c("(011) 4281 9176", "(32)2819176", "(32)281 9176")
str_view(telefonos, "\\(\\d\\d\\) \\d\\d\\d \\d\\d \\d\\d")
```

```{r}
#2.10.1 Describe los equivalentes de ?, +, * en el formato {m,n}.
# ? = {0,1} = una sola coincidencia
# + = {1,} = uno o más coincidencias
# * = {0,}= cero o más coincidencias
```

```{r}
# Describe en palabras con qué coincidiría cada una de estas expresiones regulares: (lee con atención para ver si estamos utilizando una expresión regular o una cadena que define una expresión regular.)
# 
# ^.*$   empieza con cualquier caracter y termina con *
cadena <- c("123", "una palabra", "estas son cuatro palabras", " ", "")
str_match(cadena, "^.*$")

# "\\{.+\\}"  expresion regular busca que empiece con llave q abre, cualquier caracter + y llave q cierra
cadena <- c("uno {dos} tres", "uno {} tres", "uno {2} tres")
str_view(cadena, "\\{.+\\}")

# \d{4}-\d{2}-\d{2}  se imprime como 4 dígitos - 2 dígitos - 2 digitos
#La expresión regular \d{4}-\d{2}-\d{2} coincide con secuencias de 4, 2 y 2 dígitos separados por un guión.

numeros <- c("4444-22-22", "333-22-22", "88888888")
str_view(numeros, "\\d{4}-\\d{2}-\\d{2}")

# "\\\\{4}" expresion regular busca 4\

barras <- c("\\", "\\\\", "\\\\\\", "\\\\\\\\")
str_view(barras, "\\\\{4}")
```

```{r}
# Crea expresiones regulares para buscar todas las palabras que:
# 
# Empiecen con dos consonantes.
x <- c("bba","$$xy","zzn")
  str_view(x, '^[bcdfghjklmnñpqrstvwxyz]{2}')
  str_view(x, '^[^aeiou]{2}')  #esto acepta tambien otros caracteres, no solo consonantes
  
# Tengan tres o más vocales seguidas
x <- c("aaa","$iiii","ba", "aa")  
str_view(x, '[aeiou]{3,}')
# Tengan tres o más pares de vocal-consonante seguidos.

```

```{r}
# 2.11.1 Ejercicios (resuelto en Ejercicios_cadenas)
# Describe en palabras con qué coinciden estas expresiones:
# 
# (.)\1\1
# "(.)(.)\\2\\1"
# (..)\1
# "(.).\\1.\\1"
# "(.)(.)(.).*\\3\\2\\1"
```

```{r}
# 2.11.2 Construye una expresión regular que coincida con palabras que:
# 
# Empiecen y terminen con el mismo caracter.

str_subset(c("abba", "abab", "anana", "bb"), "^(.).*\\1$") #Esta solución sirve para cualquier caracter.
str_subset(c("*bb*", "abab", "anana", "bb"), "^([:alpha:]).*\\1$") #Si quisiéramos que solo encontrara letras 
# 
# Contengan un par de letras repetido (p. ej. “nacional” tiene “na” repetidos dos veces.)
str_subset(c("abba", "abab", "anana", "bb", "abcde", "nacional"), "(..).*\\1")
# 
# Contengan una letra repetida en al menos tres lugares (p. ej. “característica” tiene tres “a”.)
str_subset(c("abbab", "abab", "anana", "bb", "nooo"), "(.).*\\1.*\\1.*")
 
```

